---
apiVersion: v1
kind: Service
metadata:
  name: sample-app
  labels:
    app: sample-app
spec:
  type: LoadBalancer
  ports:
  - name: sample-app-http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sample-app
